# Generated by Django 3.2.6 on 2021-08-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alab', '0002_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.DateField(),
        ),
    ]
